clues =[("APPLE", "Red fruit from a tree"),
        ("OCEAN", "Large body of salt water"),
        ("MUSIC", "Art of sound in time"),
        ("BOOKS", "Reading materials"),
        ("HEART", "Organ that pumps blood"),
        ("LIGHT", "Electromagnetic radiation we can see"),
        ("DANCE", "Move rhythmically to music"),
        ("PEACE", "State of harmony"),
        ("SMILE", "Happy facial expression"),
        ("DREAM", "Sequence of images during sleep"),
        ("SWIFT", "Moving very quickly"),
        ("BRAVE", "Showing courage"),
        ("GRACE", "Smooth elegant movement"),
        ("STORM", "Violent weather condition"),
        ("MAGIC", "Supernatural powers"),
        ("RIVER", "Natural flowing watercourse"),
        ("CHAIR", "Piece of furniture for sitting"),
        ("TRAIN", "Railway vehicle"),
        ("PHONE", "Communication device"),
        ("PLANT", "Living organism that grows"),
        ("STONE", "Hard solid mineral matter"),
        ("PAPER", "Material for writing"),
        ("TOWER", "Tall narrow structure"),
        ("BEACH", "Sandy or pebbly shore"),
        ("CLEAR", "Easy to see through"),
        ("FRESH", "Recently made or obtained"),
        ("SWEET", "Having a sugary taste"),
        ("WORLD", "The earth and all its inhabitants"),
        ("BREAD", "Baked food made from flour"),
        ("CLEAN", "Free from dirt"),
        ("CLOUD", "Visible mass of water vapor"),
        ("FLAME", "Hot glowing gas from fire"),
        ("GLASS", "Hard transparent material"),
        ("GRASS", "Green plants in lawns"),
        ("HOUSE", "Building for human habitation"),
        ("LAUGH", "Express amusement audibly"),
        ("MONEY", "Currency for transactions"),
        ("NIGHT", "Period of darkness"),
        ("QUIET", "Making little or no noise"),
        ("ROUND", "Shaped like a circle"),
        ("SHARP", "Having a pointed edge"),
        ("SLEEP", "Natural rest state"),
        ("SMALL", "Of limited size"),
        ("SOUND", "Vibrations that travel through air"),
        ("SPACE", "Continuous area or expanse"),
        ("SPEED", "Rate of motion"),
        ("STILL", "Not moving"),
        ("THICK", "Having great depth"),
        ("THROW", "Propel through the air"),
        ("WHEEL", "Circular frame that revolves"),
        # Adding more 5-letter words
        ("ACTOR", "Performer in plays or movies"),
        ("ADULT", "Grown-up person"),
        ("AGENT", "Representative or spy"),
        ("AGREE", "To have the same opinion"),
        ("ALARM", "Warning signal"),
        ("ALBUM", "Collection of photos or music"),
        ("ALIEN", "Being from another planet"),
        ("ALLOW", "To permit"),
        ("ALONE", "By oneself"),
        ("ALTER", "To change"),
        ("ANGEL", "Heavenly being"),
        ("ANGER", "Strong feeling of displeasure"),
        ("ANGRY", "Feeling anger"),
        ("ANKLE", "Joint between foot and leg"),
        ("APART", "Separated"),
        ("ARENA", "Sports venue"),
        ("ARGUE", "To disagree verbally"),
        ("ARISE", "To get up"),
        ("ARMED", "Carrying weapons"),
        ("ARMOR", "Protective covering"),
        ("ARROW", "Pointed projectile"),
        ("ASIDE", "To one side"),
        ("ASSET", "Valuable possession"),
        ("ATLAS", "Book of maps"),
        ("AUDIO", "Related to sound"),
        ("AUDIT", "Financial examination"),
        ("AVOID", "To stay away from"),
        ("AWAKE", "Not sleeping"),
        ("AWARD", "Prize or honor"),
        ("AWARE", "Conscious of"),
        ("BADLY", "In a bad manner"),
        ("BADGE", "Identification symbol"),
        ("BASIC", "Fundamental"),
        ("BEACH", "Sandy shore"),
        ("BEARD", "Facial hair"),
        ("BEAST", "Wild animal"),
        ("BEGIN", "To start"),
        ("BEING", "Existence"),
        ("BELLY", "Stomach area"),
        ("BELOW", "Underneath"),
        ("BENCH", "Long seat"),
        ("BERRY", "Small fruit"),
        ("BIRTH", "Being born"),
        ("BLACK", "Darkest color"),
        ("BLADE", "Sharp edge"),
        ("BLAME", "To hold responsible"),
        ("BLANK", "Empty"),
        ("BLAST", "Explosion"),
        ("BLEED", "To lose blood"),
        ("BLESS", "To make holy"),
        ("BLIND", "Unable to see"),
        ("BLOCK", "Solid piece"),
        ("BLOOD", "Red body fluid"),
        ("BLOOM", "To flower"),
        ("BOARD", "Flat piece of wood"),
        ("BOOST", "To increase"),
        ("BOOTH", "Small enclosure"),
        ("BOUND", "Tied up"),
        ("BRAIN", "Thinking organ"),
        ("BRAND", "Product name"),
        ("BRASS", "Yellow metal"),
        ("BRAVE", "Courageous"),
        ("BREAK", "To damage"),
        ("BREED", "To reproduce"),
        ("BRICK", "Building block"),
        ("BRIDE", "Woman getting married"),
        ("BRIEF", "Short"),
        ("BRING", "To carry here"),
        ("BROAD", "Wide"),
        ("BROKE", "Without money"),
        ("BROWN", "Earth color"),
        ("BRUSH", "Cleaning tool"),
        ("BUILD", "To construct"),
        ("BURST", "To explode"),
        ("BUYER", "Person who purchases"),
        ("CABLE", "Thick rope or wire"),
        ("CAMEL", "Desert animal"),
        ("CANAL", "Waterway"),
        ("CANDY", "Sweet treat"),
        ("CARRY", "To transport"),
        ("CATCH", "To grab"),
        ("CAUSE", "Reason"),
        ("CHAIN", "Series of links"),
        ("CHAOS", "Complete disorder"),
        ("CHARM", "Appeal"),
        ("CHART", "Graph or map"),
        ("CHASE", "To pursue"),
        ("CHEAP", "Inexpensive"),
        ("CHEAT", "To act dishonestly"),
        ("CHECK", "To verify"),
        ("CHEST", "Body part or box"),
        ("CHIEF", "Leader"),
        ("CHILD", "Young person"),
        ("CHINA", "Porcelain"),
        ("CHOSE", "Selected"),
        ("CIVIL", "Relating to citizens"),
        ("CLAIM", "To assert"),
        ("CLASS", "Category or lesson"),
        ("CLEAN", "Not dirty"),
        ("CLERK", "Office worker"),
        ("CLICK", "Sharp sound"),
        ("CLIMB", "To go up"),
        ("CLOCK", "Time device"),
        ("CLOSE", "Near or to shut"),
        ("CLOTH", "Fabric"),
        ("CLOUD", "Sky formation"),
        ("COACH", "Trainer"),
        ("COAST", "Shoreline"),
        ("COLOR", "Hue"),
        ("COMIC", "Funny"),
        ("COUNT", "To number"),
        ("COURT", "Legal venue"),
        ("COVER", "To hide"),
        ("CRACK", "Split"),
        ("CRAFT", "Skill"),
        ("CRASH", "Collision"),
        ("CRAZY", "Insane"),
        ("CREAM", "Dairy product"),
        ("CRIME", "Illegal act"),
        ("CRISP", "Crunchy"),
        ("CROSS", "Intersection"),
        ("CROWD", "Large group"),
        ("CROWN", "Royal headpiece"),
        ("CRUEL", "Harsh"),
        ("CRUSH", "To squash"),
        ("CURVE", "Bend"),
        ("CYCLE", "Repeating sequence"),
        ("DAILY", "Every day"),
        ("DAIRY", "Milk products"),
        ("DANCE", "Rhythmic movement"),
        ("DATED", "Old-fashioned"),
        ("DEALT", "Handled"),
        ("DEATH", "End of life"),
        ("DEBUT", "First appearance"),
        ("DELAY", "To postpone"),
        ("DEPTH", "How deep"),
        ("DERBY", "Horse race"),
        ("DEVIL", "Evil being"),
        ("DIARY", "Personal journal"),
        ("DIRTY", "Not clean"),
        ("DISCO", "Dance club"),
        ("DOING", "Acting"),
        ("DOUBT", "Uncertainty"),
        ("DOZEN", "Twelve"),
        ("DRAFT", "Preliminary version"),
        ("DRAMA", "Theatrical work"),
        ("DRANK", "Consumed liquid"),
        ("DRAWN", "Pulled"),
        ("DREAM", "Sleep vision"),
        ("DRESS", "Clothing"),
        ("DRILL", "Tool or practice"),
        ("DRINK", "Beverage"),
        ("DRIVE", "To operate vehicle"),
        ("DROVE", "Operated vehicle"),
        ("DRUGS", "Medicine"),
        ("DRUNK", "Intoxicated"),
        ("DYING", "Near death"),
        ("EAGER", "Enthusiastic"),
        ("EARLY", "Before time"),
        ("EARTH", "Our planet"),
        ("EIGHT", "Number 8"),
        ("ELBOW", "Arm joint"),
        ("ELDER", "Older person"),
        ("EMPTY", "Nothing inside"),
        ("ENEMY", "Opponent"),
        ("ENJOY", "To like"),
        ("ENTER", "To go in"),
        ("ENTRY", "Way in"),
        ("EQUAL", "Same"),
        ("ERROR", "Mistake"),
        ("EVENT", "Happening"),
        ("EVERY", "All"),
        ("EXACT", "Precise"),
        ("EXAM", "Test"),
        ("EXIST", "To be"),
        ("EXTRA", "Additional"),
        ("FAITH", "Belief"),
        ("FALSE", "Not true"),
        ("FANCY", "Elaborate"),
        ("FATAL", "Deadly"),
        ("FAULT", "Defect"),
        ("FAVOR", "Preference"),
        ("FEAST", "Large meal"),
        ("FENCE", "Barrier"),
        ("FEVER", "High temperature"),
        ("FIBER", "Thread"),
        ("FIELD", "Open area"),
        ("FIFTH", "Number 5"),
        ("FIFTY", "Number 50"),
        ("FIGHT", "Combat"),
        ("FINAL", "Last"),
        ("FIRST", "Number 1"),
        ("FIXED", "Repaired"),
        ("FLAME", "Fire"),
        ("FLASH", "Bright light"),
        ("FLESH", "Body tissue"),
        ("FLIGHT", "Flying"),
        ("FLOAT", "To stay on surface"),
        ("FLOOD", "Water overflow"),
        ("FLOOR", "Ground level"),
        ("FLOUR", "Ground grain"),
        ("FLUID", "Liquid"),
        ("FOCUS", "Concentrate"),
        ("FORCE", "Power"),
        ("FORTH", "Forward"),
        ("FORTY", "Number 40"),
        ("FOUND", "Discovered"),
        ("FRAME", "Border"),
        ("FRAUD", "Deception"),
        ("FRESH", "New"),
        ("FRONT", "Forward part"),
        ("FROST", "Ice crystals"),
        ("FRUIT", "Plant product"),
        ("FULLY", "Completely"),
        ("FUNNY", "Amusing"),
        ("GHOST", "Spirit"),
        ("GIANT", "Very large"),
        ("GIVEN", "Provided"),
        ("GLASS", "Transparent material"),
        ("GLOBE", "Sphere"),
        ("GLORY", "Honor"),
        ("GLOVE", "Hand covering"),
        ("GOING", "Moving"),
        ("GRAND", "Magnificent"),
        ("GRANT", "To give"),
        ("GRAPE", "Small fruit"),
        ("GRASS", "Green plant"),
        ("GRAVE", "Burial place"),
        ("GREAT", "Excellent"),
        ("GREEN", "Color of grass"),
        ("GREET", "To welcome"),
        ("GRIEF", "Sorrow"),
        ("GRIND", "To crush"),
        ("GROSS", "Disgusting"),
        ("GROUP", "Collection"),
        ("GROWN", "Matured"),
        ("GUARD", "Protector"),
        ("GUESS", "To estimate"),
        ("GUEST", "Visitor"),
        ("GUIDE", "Leader"),
        ("GUILT", "Feeling bad"),
        ("HABIT", "Regular behavior"),
        ("HAPPY", "Joyful"),
        ("HARSH", "Severe"),
        ("HASTE", "Speed"),
        ("HASTY", "Quick"),
        ("HEART", "Body organ"),
        ("HEAVY", "Weighing much"),
        ("HENCE", "Therefore"),
        ("HERO", "Brave person"),
        ("HORSE", "Animal"),
        ("HOTEL", "Lodging"),
        ("HOUSE", "Home"),
        ("HUMAN", "Person"),
        ("HUMOR", "Comedy"),
        ("HURRY", "To rush"),
        ("IDEAL", "Perfect"),
        ("IMAGE", "Picture"),
        ("INDEX", "List"),
        ("INNER", "Inside"),
        ("INPUT", "Data entered"),
        ("ISSUE", "Problem"),
        ("JAPAN", "Country"),
        ("JEWEL", "Precious stone"),
        ("JOINT", "Connection"),
        ("JUDGE", "Court official"),
        ("JUICE", "Fruit liquid"),
        ("KNIFE", "Cutting tool"),
        ("KNOCK", "To hit"),
        ("KNOWN", "Familiar"),
        ("LABEL", "Tag"),
        ("LABOR", "Work"),
        ("LARGE", "Big"),
        ("LASER", "Light beam"),
        ("LATER", "Afterwards"),
        ("LAUGH", "Express joy"),
        ("LAYER", "Level"),
        ("LEARN", "To study"),
        ("LEASE", "Rental agreement"),
        ("LEAST", "Smallest amount"),
        ("LEAVE", "To go away"),
        ("LEGAL", "Lawful"),
        ("LEVEL", "Height"),
        ("LIGHT", "Illumination"),
        ("LIMIT", "Boundary"),
        ("LIVER", "Body organ"),
        ("LOCAL", "Nearby"),
        ("LOOSE", "Not tight"),
        ("LOVED", "Cared for"),
        ("LOWER", "Below"),
        ("LUCKY", "Fortunate"),
        ("LUNCH", "Midday meal"),
        ("LYING", "Not truthful"),
        ("MAGIC", "Supernatural"),
        ("MAJOR", "Important"),
        ("MAKER", "Creator"),
        ("MARCH", "Third month"),
        ("MATCH", "Game or pair"),
        ("MAYBE", "Perhaps"),
        ("MAYOR", "City leader"),
        ("MEALS", "Food portions"),
        ("MEANS", "Method"),
        ("MEANT", "Intended"),
        ("MEDAL", "Award"),
        ("MEDIA", "Communication channels"),
        ("METAL", "Hard material"),
        ("MIGHT", "Power or maybe"),
        ("MINOR", "Small"),
        ("MIXED", "Combined"),
        ("MODEL", "Example"),
        ("MONEY", "Currency"),
        ("MONTH", "Time period"),
        ("MORAL", "Ethical"),
        ("MOTOR", "Engine"),
        ("MOUNT", "To climb"),
        ("MOUSE", "Small rodent"),
        ("MOUTH", "Oral opening"),
        ("MOVED", "Changed position"),
        ("MOVIE", "Film"),
        ("MUSIC", "Sound art"),
        ("NAKED", "Without clothes"),
        ("NAMED", "Called"),
        ("NASTY", "Unpleasant"),
        ("NEEDS", "Requirements"),
        ("NERVE", "Body fiber"),
        ("NEVER", "Not ever"),
        ("NEWLY", "Recently"),
        ("NIGHT", "Dark period"),
        ("NOISE", "Sound"),
        ("NORTH", "Direction"),
        ("NOTED", "Famous"),
        ("NOVEL", "Book"),
        ("NURSE", "Medical helper"),
        ("OCCUR", "To happen"),
        ("OCEAN", "Large water body"),
        ("OFFER", "To propose"),
        ("OFTEN", "Frequently"),
        ("OLDER", "More aged"),
        ("OLIVE", "Small fruit"),
        ("ONION", "Vegetable"),
        ("OPERA", "Musical drama"),
        ("ORDER", "Sequence"),
        ("ORGAN", "Body part"),
        ("OTHER", "Different"),
        ("OUGHT", "Should"),
        ("OUTER", "Outside"),
        ("OWNED", "Possessed"),
        ("OWNER", "Possessor"),
        ("PAINT", "Coloring material"),
        ("PANEL", "Flat surface"),
        ("PAPER", "Writing material"),
        ("PARTY", "Celebration"),
        ("PASTA", "Italian food"),
        ("PATCH", "Small piece"),
        ("PAUSE", "To stop briefly"),
        ("PEACE", "Harmony"),
        ("PEACH", "Fruit"),
        ("PHASE", "Stage"),
        ("PHONE", "Communication device"),
        ("PHOTO", "Picture"),
        ("PIANO", "Musical instrument"),
        ("PIECE", "Part"),
        ("PILOT", "Aircraft operator"),
        ("PITCH", "Throw or tone"),
        ("PIZZA", "Italian dish"),
        ("PLACE", "Location"),
        ("PLAIN", "Simple"),
        ("PLANE", "Aircraft"),
        ("PLANT", "Growing organism"),
        ("PANDA", "Black and white bear"),
        ("PEARL", "Gem formed inside an oyster"),
        ("PLATE", "Dish"),
        ("PLAZA", "Public square"),
        ("POEM", "Verse"),
        ("POINT", "Dot or purpose"),
        ("POUND", "Weight unit"),
        ("POWER", "Energy"),
        ("PRESS", "To push"),
        ("PRICE", "Cost"),
        ("PRIDE", "Self-respect"),
        ("PRIME", "Best"),
        ("PRINT", "To publish"),
        ("PRIOR", "Before"),
        ("PRIZE", "fees"),

        ("QUACK", "Sound made by a duck"),
    ("QUILT", "Blanket made from fabric pieces"),
    ("QUIET", "Lacking noise or sound"),
    ("QUICK", "Fast or speedy"),
    ("QUERY", "A question or inquiry"),
    
    ("RANCH", "Farm with livestock"),
    ("RANGE", "Scope or extent"),
    ("REACT", "To respond to stimulus"),
    ("REBEL", "One who resists authority"),
    ("RIDER", "Person on a horse or bike"),
    ("RIVER", "Natural flowing watercourse"),
    ("ROBOT", "Machine that performs tasks"),
    ("ROCKY", "Full of rocks or rugged"),
    ("ROAST", "To cook over dry heat"),
    ("RULER", "Measuring tool or monarch"),
    
    ("SCALE", "Instrument for measuring weight"),
    ("SCARE", "To frighten someone"),
    ("SCENE", "Part of a play or setting"),
    ("SHEEP", "Wool-producing animal"),
    ("SHINE", "To glow or reflect light"),
    ("SHORE", "Land by a body of water"),
    ("SLEEP", "Rest with closed eyes"),
    ("SLOPE", "Surface that slants upward/downward"),
    ("SMILE", "Expression of happiness"),
    ("SNAKE", "Long, legless reptile"),
    ("SOUND", "Noise or vibration"),
    ("SPOON", "Utensil for eating"),
    ("SPINE", "Backbone"),
    ("SPORT", "Physical competitive activity"),
    ("STEEL", "Strong metal alloy"),
    ("STONE", "Small rock or mineral"),
    ("STORM", "Severe weather with rain/wind"),
    ("STYLE", "Manner of doing or looking"),
    
    ("TASTE", "Sense used with the tongue"),
    ("TEACH", "To impart knowledge"),
    ("TEETH", "Hard parts in the mouth"),
    ("TIGER", "Striped big cat"),
    ("TOAST", "Browned bread"),
    ("TOOTH", "Single unit in a mouth"),
    ("TRACK", "Path or trail"),
    ("TRAIN", "Connected railroad cars"),
    ("TRICK", "Deceitful or clever act"),
    ("TRUCK", "Heavy road vehicle"),
    
    ("UNCLE", "Mother or father's brother"),
    ("UNDER", "Below something"),
    ("UNION", "Joining of parts"),
    ("URBAN", "Related to cities"),
    ("USAGE", "The way something is used"),
    ("USUAL", "Common or habitual"),
    
    ("VIRUS", "Microscopic infectious agent"),
    ("VITAL", "Very important"),
    ("VOTER", "One who casts a ballot"),
    ("VOICE", "Sound from the mouth"),
    ("VENOM", "Poison from animals"),
    
    ("WAGON", "Four-wheeled vehicle"),
    ("WASTE", "Unwanted or unused material"),
    ("WATER", "Clear liquid essential for life"),
    ("WHALE", "Large ocean mammal"),
    ("WHEAT", "Cereal grain crop"),
    ("WOMAN", "Adult female human"),
    ("WORLD", "Earth or human civilization"),
    ("WOUND", "Injury to body"),
    
    ("YACHT", "Luxury boat"),
    ("YEAST", "Fungus used in baking"),
    ("YOUNG", "Not old"),
    ("YOUTH", "Period of being young"),
    ("YELLS", "Shouts loudly"),
    
    ("ZEBRA", "Striped African animal"),
    ("ZONED", "Divided into areas"),
    ("ZESTY", "Full of flavor or energy"),
    ("ZIPPY", "Lively or energetic"),
    ("ZONAL", "Relating to zones")]